name: Install with flit and test via Pytest

on:
  push:
    paths:
    - '**.py' # only run workflow when source files changed 
    - '**.yml'
    - 'requirements.txt'
    - 'pyproject.toml'
    branches:
    - "**"
    tags-ignore:
    - "*.*.*"
  pull_request: # Run in every PR
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      fail-fast: true
      matrix:
         os: [ubuntu-latest] # much slower on Mac and Win, but can use [ubuntu-latest, macos-latest, windows-latest]
         python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Check Black code style
      uses: psf/black@stable #https://black.readthedocs.io/en/stable/integrations/github_actions.html
    
    - name: Upgrade pip, install dependencies
      shell: bash {0}
      run: |
        pip install --upgrade pip
        pip install flit torch
        pip install numba==0.53.* numpy==1.22.0
        pip install megnet
        flit install
    - name: Test with Pytest on MacOS or Ubuntu
      shell: bash {0}
      if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
      run: |
        export NUMBA_ENABLE_CUDASIM=1
        python -m pytest
    - name: Test with Pytest on Windows
      shell: bash {0}
      if: startsWith(matrix.os, 'windows')
      run: |
        set NUMBA_ENABLE_CUDASIM=1
        python -m pytest
        
#     - name: publish-to-conda # requires setup.py file
#       uses: fcakyon/conda-publish-action@v1.3
#       with:
#         subdir: 'conda'
#         anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
#         platforms: 'win osx linux'

#       with:
#         submodules: recursive

# pip install psutil==5.8.0 virtualenv==20.11.0 Pygments==2.11.1 zipp==3.6.0 jsonschema==4.3.2 attrs==21.3.0
# pip install oldest-supported-numpy # might need to go into pyproject.toml requires instead
# pip install torch==1.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
# flit install --deps production --extras test

# NOTES:
# needed to use python instead of python3 for Windows https://stackoverflow.com/questions/61558780/python-testing-with-github-actions-on-windows
# also needed to remove the -l from the shell so it didn't interfere with MacOS PATH calling Python 2.7
